In [33]:
import pandas as pd

In [34]:
def letter_counter(string, type=None):
    if (type == 'c'):
        return {letter: str(string).count(letter) for letter in 'bcdfghjklmnpqrstvwxyz'}
    elif (type == 'v'):
        return {letter: str(string).count(letter) for letter in 'aeiou'}  
    return {letter: str(string).count(letter) for letter in 'abcdefghijklmnopqrstuvwxyz'}

def type_counter(string, type):    
    return sum(letter_counter(string, type).values())

def type_ratio(string, type):
    return type_counter(string, type)/len(string)

def repetitions_character(repetitions, caractere):
        x = repetitions.get(caractere)
        return x if x != None else 0
    
def repetitions(string):
    try:
        resultados = []
        size = len(string)
        valor = 1

        for l in range(0, size):
            if l <= size-2 and string[l] == string[l+1]:
                valor += 1
            else:
                resultados.append(tuple((string[l], valor)))
                valor = 1
        return dict(sorted(resultados))
    except:
        return {}

def repetitions_type(string, type):
    if type == 'c':
        letters = 'bcdfghjklmnpqrstvwxyz'
    else:
        letters = 'aeiou'
    
    resultados = []
    size = len(string)
    valor = 0

    for l in string:
        if l in letters:
            valor += 1
        else:
            resultados.append(valor)
            valor = 0
    resultados.append(valor)
    
    return max(resultados)

def bigram_counter(lista):
  dic = {}
  for i in lista:
    if i in dic:
      dic[i] +=1
    else:
      dic[i] =1
  return dic

def bigrams(string):
    bigrams = []
    for i in range(len(string)-1):
        bigrams.append(string[i]+string[i+1])

    return bigram_counter(bigrams)

def bigram_max_occurance(string):
    try:
        return (sorted(bigrams(string).values(), reverse=True))[0]
    except:
        return 0

In [35]:
# Letras
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

# Tamanho da string
keys = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', 
        '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '27', '28', '29', '31']

# Index que começa cada categoria
values = [0, 26, 453, 2584, 9769, 25689, 55563, 97561, 149188, 202590, 248462, 286001, 
          315126, 336070, 350219, 359065, 364247, 367214, 368685, 369445, 369804, 369972, 
          370046, 370077, 370089, 370097, 370100, 370102, 370104]

# Dicionário em forma de lista
items = [('1', 0), ('2', 26), ('3', 453), ('4', 2584), ('5', 9769), 
         ('6', 25689), ('7', 55563), ('8', 97561), ('9', 149188),('10', 202590), 
         ('11', 248462), ('12', 286001), ('13', 315126), ('14', 336070), ('15', 350219), 
         ('16', 359065), ('17', 364247), ('18', 367214), ('19', 368685), ('20', 369445), 
         ('21', 369804), ('22', 369972), ('23', 370046), ('24', 370077), ('25', 370089), 
         ('27', 370097), ('28', 370100), ('29', 370102), ('31', 370104)]

In [36]:
df = pd.read_csv("../data/raw/words.csv")

# Análise de média de vogais e consoantes

In [37]:
aux = df.copy()
aux["len"] = aux["words"].apply(lambda x : len(str(x)))
aux["vowel rt"] = aux["words"].apply(lambda x : type_ratio(str(x), 'v'))
aux["consonant rt"] = aux["vowel rt"].apply(lambda x : 1-x)

In [38]:
aux.sort_values(by=['len', 'words'], inplace=True, ignore_index=True)
aux

                                  words  len  vowel rt  consonant rt
0                                     a    1  1.000000      0.000000
1                                     b    1  0.000000      1.000000
2                                     c    1  0.000000      1.000000
3                                     d    1  0.000000      1.000000
4                                     e    1  1.000000      0.000000
...                                 ...  ...       ...           ...
370100     antidisestablishmentarianism   28  0.392857      0.607143
370101     hydroxydehydrocorticosterone   28  0.321429      0.678571
370102    cyclotrimethylenetrinitramine   29  0.344828      0.655172
370103    trinitrophenylmethylnitramine   29  0.310345      0.689655
370104  dichlorodiphenyltrichloroethane   31  0.354839      0.645161

[370105 rows x 4 columns]

In [39]:
newdf = pd.DataFrame()
rows = ["min vowel rt", "max vowel rt", "min consonant rt", "max consonant rt"]
newdf.insert(0, "len", rows)

In [40]:
def analysys_by_len_rt(df, newdf, len, column):
    to_append = []
    index = keys.index(f'{len}')
    
    try:    
        # vrt_min
        to_append.append(min(df['vowel rt'][items[index][1]:items[index+1][1]]))
        # vrt_max
        to_append.append(max(df['vowel rt'][items[index][1]:items[index+1][1]]))
        # crt_min
        to_append.append(min(df['consonant rt'][items[index][1]:items[index+1][1]]))
        # crt_max
        to_append.append(max(df['consonant rt'][items[index][1]:items[index+1][1]]))

    except:
        # vrt_min
        to_append.append(df['vowel rt'][items[index][1]])
        # vrt_max
        to_append.append(df['vowel rt'][items[index][1]])
        # crt_min
        to_append.append(df['consonant rt'][items[index][1]])
        # crt_max
        to_append.append(df['consonant rt'][items[index][1]])
    
    newdf.insert(int(column), f"{len}", to_append)

In [41]:
column = 0
for i in keys:
    analysys_by_len_rt(aux, newdf, i, column)
    column += 1

newdf.set_index('len', inplace=True)

newdf

,1,2,3,4,5,6,7,8,9,10,...,20,21,22,23,24,25,27,28,29,31
len,,,,,,,,,,,,,,,,,,,,,
min vowel rt,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.00,0.111111,0.1,...,0.25,0.238095,0.272727,0.304348,0.333333,0.28,0.333333,0.321429,0.310345,0.354839
max vowel rt,1.0,1.0,1.0,1.0,0.8,1.0,0.857143,0.75,0.777778,0.7,...,0.55,0.571429,0.500000,0.478261,0.458333,0.40,0.370370,0.392857,0.344828,0.354839
min consonant rt,0.0,0.0,0.0,0.0,0.2,0.0,0.142857,0.25,0.222222,0.3,...,0.45,0.428571,0.500000,0.521739,0.541667,0.60,0.629630,0.607143,0.655172,0.645161
max consonant rt,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,1.00,0.888889,0.9,...,0.75,0.761905,0.727273,0.695652,0.666667,0.72,0.666667,0.678571,0.689655,0.645161

In [42]:
newdf.to_csv("../data/processed/analise_v&c_rt.csv")

# Análise contagem de letras

In [43]:
aux = df.copy()
aux["len"] = aux["words"].apply(lambda x : len(str(x)))
for letter in letters:
    aux[f"{letter}"] = aux["words"].apply(lambda x : letter_counter(str(x))[f'{letter}'])

In [44]:
aux.sort_values(by=['len', 'words'], inplace=True, ignore_index=True)
aux

,words,len,a,b,c,d,e,f,g,h,...,q,r,s,t,u,v,w,x,y,z
0,a,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,b,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,c,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,d,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,e,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370100,antidisestablishmentarianism,28,4,1,0,1,2,0,0,1,...,0,1,4,3,0,0,0,0,0,0
370101,hydroxydehydrocorticosterone,28,0,0,2,3,3,0,0,2,...,0,4,1,2,0,0,0,1,3,0
370102,cyclotrimethylenetrinitramine,29,1,0,2,0,4,0,0,1,...,0,3,0,4,0,0,0,0,2,0
370103,trinitrophenylmethylnitramine,29,1,0,0,0,3,0,0,2,...,0,3,0,4,0,0,0,0,2,0
370104,dichlorodiphenyltrichloroethane,31,1,0,2,2,3,0,0,4,...,0,3,0,2,0,0,0,0,1,0

In [45]:
maxdf = pd.DataFrame()
maxdf.insert(0, "len", letters)

In [46]:
def analysys_by_len_letters(df, maxdf,len, column):
    to_append_max = []
    index = keys.index(f'{len}')
    
    try:    
       for letter in letters:
            to_append_max.append(max(df[f'{letter}'][items[index][1]:items[index+1][1]]))
       
    except:
        for letter in letters:
            to_append_max.append(df[f'{letter}'][items[index][1]])
    
    maxdf.insert(int(column), f"{len}", to_append_max)

In [47]:
column = 0
for i in keys:
    analysys_by_len_letters(aux, maxdf, i, column)
    column += 1

maxdf.set_index('len', inplace=True)

In [48]:
maxdf

,1,2,3,4,5,6,7,8,9,10,...,20,21,22,23,24,25,27,28,29,31
len,,,,,,,,,,,,,,,,,,,,,
a,1,2,3,2,3,3,4,4,5,5,...,5,4,4,4,3,4,3,4,1,1
b,1,2,2,3,3,3,3,3,4,4,...,2,2,2,1,2,1,0,1,0,0
c,1,2,2,2,3,4,3,4,4,4,...,4,4,3,3,3,3,3,2,2,2
d,1,2,2,3,3,4,4,4,4,4,...,3,3,3,3,2,1,2,3,0,2
e,1,2,2,3,3,4,4,4,5,5,...,5,6,7,5,4,7,4,3,4,3
f,1,2,2,3,3,3,3,4,4,4,...,2,1,2,2,1,0,0,0,0,0
g,1,1,2,3,3,3,4,4,4,4,...,3,2,2,2,2,2,1,0,0,0
h,1,1,2,2,2,3,3,4,3,3,...,3,4,3,4,3,3,2,2,2,4
i,1,2,3,3,3,3,3,4,4,4,...,6,5,5,6,5,4,2,5,4,3
j,1,1,1,2,2,2,2,2,2,2,...,2,2,1,0,0,0,0,0,0,0
k,1,1,1,2,3,4,2,3,3,4,...,1,2,1,0,0,0,0,0,0,0
l,1,2,2,3,3,3,4,4,4,4,...,5,5,4,3,3,3,4,1,2,3
m,1,2,2,4,3,3,3,4,4,4,...,3,3,2,2,2,2,2,2,2,0
n,1,1,2,2,3,3,4,4,5,5,...,6,4,5,3,3,3,1,3,4,2
o,1,1,2,4,3,4,4,5,4,4,...,5,6,6,5,5,5,5,5,1,4
p,1,2,2,2,3,3,3,3,4,4,...,3,3,3,3,2,3,2,0,1,1
q,1,1,2,2,1,2,1,2,2,2,...,1,0,1,0,0,0,0,0,0,0
r,1,1,2,3,3,3,3,4,4,4,...,4,4,3,6,4,6,3,4,3,3
s,1,2,2,3,3,4,4,5,5,5,...,5,5,4,4,4,4,2,4,0,0
t,1,1,2,2,3,3,4,4,4,4,...,5,5,4,5,4,3,3,3,4,2
u,1,1,2,2,3,4,4,4,4,4,...,3,9,2,1,2,1,0,0,0,0
v,1,2,2,2,2,3,2,2,2,3,...,3,2,2,2,0,0,0,0,0,0
w,1,1,2,2,2,3,4,3,3,3,...,0,1,1,0,0,0,0,0,0,0
x,1,2,3,2,2,2,2,2,2,2,...,1,2,3,1,1,0,2,1,0,0
y,1,1,2,2,2,3,3,3,3,3,...,3,4,4,3,2,2,3,3,2,1
z,1,1,1,3,2,3,4,3,4,4,...,2,2,1,1,1,0,0,0,0,0

In [49]:
maxdf.to_csv("../data/processed/analise_count_max.csv")

# Análise repetição de bigramas

In [50]:
aux = df.copy()
aux["len"] = aux["words"].apply(lambda x : len(str(x)))
aux["max bigram occ."] = aux["words"].apply(lambda x : bigram_max_occurance(str(x)))

In [51]:
aux.sort_values(by=['max bigram occ.', 'words'], inplace=True, ignore_index=True)

In [52]:
aux["max bigram occ."].max()

4

Notou-se que ocorrência máxima do mesmo bigrama é 4, contudo, só 7 palavras apresentam essa característica, logo, pode-se concluir que a partir de três pode-se deduzir que é um keyboad smashing. Também notu-se que somente cerca de 1000 palavras possuem a ocorrência máxima de 3 bigramas, e que a menor palavra que a possui, tem 4 letras.

# Análise cadeia de repetições

In [53]:
aux = df.copy()
aux["len"] = aux["words"].apply(lambda x : len(str(x)))
for letter in letters:
    aux[f"{letter}"] = aux["words"].apply(lambda x : repetitions_character(repetitions(str(x)), letter))

In [54]:
aux.sort_values(by=['len', 'words'], inplace=True, ignore_index=True)
aux

,words,len,a,b,c,d,e,f,g,h,...,q,r,s,t,u,v,w,x,y,z
0,a,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,b,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,c,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,d,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,e,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370100,antidisestablishmentarianism,28,1,1,0,1,1,0,0,1,...,0,1,1,1,0,0,0,0,0,0
370101,hydroxydehydrocorticosterone,28,0,0,1,1,1,0,0,1,...,0,1,1,1,0,0,0,1,1,0
370102,cyclotrimethylenetrinitramine,29,1,0,1,0,1,0,0,1,...,0,1,0,1,0,0,0,0,1,0
370103,trinitrophenylmethylnitramine,29,1,0,0,0,1,0,0,1,...,0,1,0,1,0,0,0,0,1,0
370104,dichlorodiphenyltrichloroethane,31,1,0,1,1,1,0,0,1,...,0,1,0,1,0,0,0,0,1,0

In [55]:
newdf = pd.DataFrame()
newdf.insert(0, "len", letters)

In [56]:
def analysys_by_len_repetition(df, newdf, len, column):
    to_append = []
    index = keys.index(f'{len}')

    try:    
        for letter in letters:
            to_append.append(max(df[f'{letter}'][items[index][1]:items[index+1][1]]))
    except:
        for letter in letters:
            to_append.append(df[f'{letter}'][items[index][1]])
    
    newdf.insert(int(column), f"{len}", to_append)

In [57]:
column = 0
for i in keys:
    analysys_by_len_repetition(aux, newdf, i, column)
    column += 1

newdf.set_index('len', inplace=True)
newdf

,1,2,3,4,5,6,7,8,9,10,...,20,21,22,23,24,25,27,28,29,31
len,,,,,,,,,,,,,,,,,,,,,
a,1,2,3,2,2,2,2,2,2,2,...,1,2,1,1,1,1,1,1,1,1
b,1,2,2,2,2,2,2,2,2,2,...,1,1,2,1,1,1,0,1,0,0
c,1,2,2,2,2,2,2,2,3,2,...,2,2,2,1,1,1,1,1,1,1
d,1,2,2,2,3,2,2,2,2,2,...,2,1,1,1,1,1,1,1,0,1
e,1,2,2,3,2,2,2,2,3,2,...,1,1,1,1,1,1,1,1,1,1
f,1,2,2,2,2,2,2,2,2,2,...,2,1,1,1,1,0,0,0,0,0
g,1,1,2,2,2,2,2,2,2,2,...,2,1,1,1,1,1,1,0,0,0
h,1,1,2,2,1,1,2,2,2,2,...,1,1,1,1,1,1,1,1,1,1
i,1,2,3,3,3,2,2,2,2,2,...,2,2,1,1,1,1,1,1,1,1
j,1,1,1,2,2,2,1,1,2,1,...,1,1,1,0,0,0,0,0,0,0
k,1,1,1,2,2,2,2,2,2,2,...,1,1,1,0,0,0,0,0,0,0
l,1,2,2,2,2,2,2,3,3,2,...,2,2,2,2,2,2,2,1,1,1
m,1,2,2,4,2,2,2,2,2,2,...,2,2,2,1,1,2,1,1,1,0
n,1,1,2,2,2,3,3,2,2,2,...,2,2,2,1,1,1,1,1,1,1
o,1,1,2,4,2,2,2,2,2,2,...,2,1,2,1,1,1,1,1,1,1
p,1,2,2,2,2,3,2,3,3,3,...,2,2,1,1,1,1,1,0,1,1
q,1,1,2,2,1,2,1,1,1,1,...,1,0,1,0,0,0,0,0,0,0
r,1,1,2,3,2,2,2,2,2,2,...,2,2,2,2,1,1,1,1,1,1
s,1,2,2,2,2,2,2,3,2,3,...,2,2,2,1,1,2,1,1,0,0
t,1,1,2,2,2,2,3,3,2,2,...,1,2,1,1,1,1,1,1,1,1
u,1,1,2,2,2,2,2,2,2,2,...,1,1,1,1,1,1,0,0,0,0
v,1,2,1,2,2,2,2,2,2,1,...,1,1,1,1,0,0,0,0,0,0
w,1,1,1,1,1,2,2,2,2,2,...,0,1,1,0,0,0,0,0,0,0
x,1,2,3,2,2,1,1,1,1,1,...,1,1,1,1,1,0,1,1,0,0
y,1,1,1,1,1,2,2,2,1,2,...,1,1,1,1,1,1,1,1,1,1
z,1,1,1,2,2,2,2,2,2,2,...,1,1,1,1,1,0,0,0,0,0

In [58]:
newdf.to_csv("../data/processed/analise_len_cadeias.csv")

# Análise cadeia de repetições de consoantes e vogais

In [59]:
aux = df.copy()
aux["len"] = aux["words"].apply(lambda x : len(str(x)))
aux["vowel rp"] = aux["words"].apply(lambda x : repetitions_type(str(x), 'v'))
aux["consonant rp"] = aux["words"].apply(lambda x : repetitions_type(str(x), 'c'))

In [60]:
aux.sort_values(by=['len', 'words'], inplace=True, ignore_index=True)
aux

                                  words  len  vowel rp  consonant rp
0                                     a    1         1             0
1                                     b    1         0             1
2                                     c    1         0             1
3                                     d    1         0             1
4                                     e    1         1             0
...                                 ...  ...       ...           ...
370100     antidisestablishmentarianism   28         2             3
370101     hydroxydehydrocorticosterone   28         1             4
370102    cyclotrimethylenetrinitramine   29         1             4
370103    trinitrophenylmethylnitramine   29         1             5
370104  dichlorodiphenyltrichloroethane   31         2             5

[370105 rows x 4 columns]

In [61]:
newdf = pd.DataFrame()
rows = ["vowel rp", "consonant rp"]
newdf.insert(0, "len", rows)

In [62]:
def analysys_by_len_repetition_type(df, newdf, len, column):
    to_append = []
    index = keys.index(f'{len}')
    
    try:    
        to_append.append(max(df['vowel rp'][items[index][1]:items[index+1][1]]))
        to_append.append(max(df['consonant rp'][items[index][1]:items[index+1][1]]))
        
    except:
        to_append.append(df['vowel rp'][items[index][1]])
        to_append.append(df['consonant rp'][items[index][1]])
    
    newdf.insert(int(column), f"{len}", to_append)

In [63]:
column = 0
for i in keys:
    analysys_by_len_repetition_type(aux, newdf, i, column)
    column += 1

newdf.set_index('len', inplace=True)
newdf

,1,2,3,4,5,6,7,8,9,10,...,20,21,22,23,24,25,27,28,29,31
len,,,,,,,,,,,,,,,,,,,,,
vowel rp,1,2,3,4,4,6,5,5,5,4,...,4,3,3,2,3,2,2,2,1,2
consonant rp,1,2,3,4,5,6,7,8,8,8,...,7,7,7,6,5,7,4,4,5,5

In [64]:
newdf.to_csv("../data/processed/analise_len_cadeia_por_tipo.csv")